### ISSUE TITLE
Plugability to integrate different monitoring and logging solution other than Riemann and ELK. 

### ISSUE THREAD

**Issue by subhankarc** [cloudfoundry-incubator/service-fabrik-broker#14]
Currently, for Monitoring, SF provides plug-ability for only Riemann. Same is the case for logging, as it only can send logs to ELK stack. SF should build plugin mechanism to talk to multiple monitoring and logging solutions and it should easy to integrate such a system.

**Comment by anoopjb** [comment]
De scoped.
