### ISSUE TITLE
IaaS errors are not bubbled up

### ISSUE THREAD

**Issue by muralisc** [cloudfoundry-incubator/service-fabrik-broker#228]
**Description**

The error thrown by IaaS while deleting snapshot is not bubbled up.
https://github.com/cloudfoundry-incubator/service-fabrik-broker/blob/master/lib/iaas/CloudProviderClient.js#L179

**Steps to reproduce the issue:**
1. Create a backup
2. Delete the snapshot directly from the IaaS
3. Try deleting the backup

**Describe the results you received:**
The backup gets deleted.

**Describe the results you expected:**
The backup should not be deleted and a valid error should be thrown

**Comment by subhankarc** [comment]
@muralisc closing it as PR is merged.
