### ISSUE TITLE
Add support for service instance sharing

### ISSUE THREAD

**Issue by jenspinney** [cloudfoundry-incubator/service-fabrik-broker#251]
A new feature allowing service instances to be shared across orgs and spaces was released in cf-deployment version 1.10.0. [This doc](https://docs.cloudfoundry.org/services/enable-sharing.html) explains the very simple step required to enable this feature for your service (adding a `shareable` field to your service-level metadata in the catalog). Have you thought about enabling this for your service?

**Comment by kamath-prasad** [comment]
@jenspinney : We will check this option and get back to you .
