### ISSUE TITLE
Enabling service-fabrik to communicate with UAA enabled Bosh director 

### ISSUE THREAD

**Issue by jayeshjk** [cloudfoundry-incubator/service-fabrik-broker#353]
* Bosh director supports following two authentication mechanisms: Basic and token based.
* For token based authentication, bosh uses a separate UAA server, which is generally deployed alongside director. 
* SF (Service-Fabrik) has multiple communication points with Bosh as it primarily supports Bosh based service instance provisioning. Currently SF supports only basic authentication while communicating with Bosh Director, which might be serious problem as Bosh supports only one kind of authentication at any point of time.
* Hence SF must have support for both authentication mechanisms while communicating with involved Bosh directors.

**Comment by subhankarc** [comment]
@jayeshjk Closing it as the referenced PR is merged.
