### ISSUE TITLE
support for non pitr based services 

### ISSUE THREAD

**Issue by sauravmndl** [cloudfoundry-incubator/service-fabrik-broker#360]
**Description**
Service Fabrik needs to support for non-PITR service. But the service has feature backup/restore. 
Following two scenarios need to support

1. Restore quota check need not be there for non-PITR service
2. After restore, backup should not be triggered for non-PITR service

**Comment by subhankarc** [comment]
@sauravmndl I believe it is resolved now. Closing it.
