### ISSUE TITLE
Service specific Deployment Status

### ISSUE THREAD

**Issue by welfwalter** [cloudfoundry-incubator/service-fabrik-broker#389]
After Cloud Foundry's Cloud Controller has sent the service provisioning request to Service Fabrik, it polls for the status.
When the Service Fabrik triggered bosh and bosh finished the deployment, the Service Fabrik sends back the status "Created".

But for some services, some further initialization are then still necessary. These may take a while before the service is really consumable.
In Cloud Cockpit we would then still want to see status "Creating". (Or maybe an additional status like "Finalizing".)
So we would like to have the possibility to control which status is returned from Service Fabrik to Cloud Controller – specific for a service.
 
A possible implementation could be a new method “getDeploymentStatus” in the Service Fabrik Agent API.

**Comment by subhankarc** [comment]
@welfwalter For asynchronous service provisioning, initial create request is responded with 202 and then platform(cloud controller) starts polling for the last operation. According to the OSBAPI [spec](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#polling-last-operation-for-service-instances) the broker should return state as part of the body and [here](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#body-1) it mentions that `the valid values are in progress, succeeded, and failed`.

So, I don't think we can send anything else other than in progress where the service instance is not yet ready to be used.

To support the use-case you have, I could think of some post processing hook which polls agent for its readiness and then sets the status as succeeded.

@jagadish-kb please let us know your view.

**Comment by welfwalter** [comment]
Hi subhankarc,
if the list of status is fixed to these three values then the value should stay as `in progress`.
The post processing hook polling the agent sounds fine.
With regards
 Welf
